/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var myArray = [1, 2];

while (myArray[myArray.length-1] < 4000000) {
	myArray[myArray.length] = myArray[myArray.length-1] + myArray[myArray.length-2];
}

var evens = [];

for (i = 0; i < myArray.length; i++) {
	if (myArray[i] % 2 == 0) {
		evens[evens.length] = myArray[i];
	}
}

var sum = 0;
for (i = 0; i < evens.length; i++) {
	sum += evens[i];
}

console.log(sum); /* Correct answer: 4613732 */